export enum Api {
  BaseAuthApi = 'auth/oauth/token?_allow_anonymous=true',
  BaseAntIconApi = 'api/supply-service/ant-icon/',
  BaseUserApi = 'api/supply-service/user/',
  BaseRoleApi = 'api/supply-service/role/',
  BaseDictApi = 'api/supply-service/dict/',
  BaseAntMenuApi = 'api/supply-service/ant-menu/',
  BaseDeptApi = 'api/supply-service/dept/',
  BaseSupplyApi = 'api/supply-service/',
  BaseSupplyAdsApi= 'api/supply-service/ads/',
  BaseSupplyAnnouncementApi= 'api/supply-service/announcement/',
  BaseSupplyFirmApi = 'api/supply-service/firm/',
  BaseSupplyMarketApi = 'api/supply-service/marketOrder/',
  BaseSupplyPurchaseApi = 'api/supply-service/purchaseOrder/',
  BaseSupplyMaterialApi = 'api/supply-service/firm/material/',
  BaseSupplyUserApi = 'api/supply-service/firm/user',
  BaseSupplyUserApplyApi = 'api/supply-service/firm/user/apply',
  BaseSupplyUserAccessApi = 'api/supply-service/firm/user/access',
  BaseSupplySupplierApi = 'api/supply-service/firm/supplier',
  BaseSupplyConsumerApi = 'api/supply-service/firm/consumer',
  BaseSupplyOrderFlowApi= 'api/supply-service/flow',
  FirmUserJoinedUrl= 'api/supply-service/firm/user/firm/list',
  BaseSupplyDeliverUrl = 'api/supply-service/deliver/',
  BaseSupplyOrderChangeUrl = 'api/supply-service/change/',
  BaseSupplyMyConsumerUrl = 'api/supply-service/myConsumer'
}
