export enum Api {
  BaseAuthApi = 'auth/oauth/token?_allow_anonymous=true',
  BaseAntIconApi = 'api/portal-service/ant-icon/',
  BaseUserApi = 'api/user-service/user/',
  BaseRoleApi = 'api/portal-service/role/',
  BaseDictApi = 'api/portal-service/dict/',
  BaseAntMenuApi = 'api/portal-service/ant-menu/',
  BaseDeptApi = 'api/portal-service/dept/',
  BaseSupplyApi = 'api/supply-service/',
  BaseSupplyFirmApi = 'api/supply-service/firm/',
  BaseSupplyMarketApi = 'api/supply-service/marketOrder/',
  BaseSupplyPurchaseApi = 'api/supply-service/purchaseOrder/',
  BaseSupplyMaterialApi = 'api/supply-service/firm/material/',
  BaseSupplyUserApi = 'api/supply-service/firm/user',
  BaseSupplySupplierApi = 'api/supply-service/firm/supplier',
  BaseSupplyConsumerApi = 'api/supply-service/firm/consumer',
}
